import {
  AccountDto,
  CategoryGroupDto,
  CategoryDto,
  TransactionDto,
  BudgetDto,
  RuleDto,
  RecurringItemDto,
  NetWorthPoint,
} from "@/types";

export const SEED_CATEGORY_GROUPS: CategoryGroupDto[] = [
  {
    id: "cg-income",
    name: "Income",
    type: "INCOME",
    sortOrder: 1,
    categories: [],
  },
  {
    id: "cg-fixed",
    name: "Fixed Expenses",
    type: "FIXED_EXPENSE",
    sortOrder: 2,
    categories: [],
  },
  {
    id: "cg-variable",
    name: "Variable Expenses",
    type: "VARIABLE_EXPENSE",
    sortOrder: 3,
    categories: [],
  },
  {
    id: "cg-nonmonthly",
    name: "Non-Monthly / Discretionary",
    type: "NON_MONTHLY",
    sortOrder: 4,
    categories: [],
  },
];

export const SEED_CATEGORIES: CategoryDto[] = [
  // Income
  { id: "cat-paycheck", groupId: "cg-income", name: "Paycheck / Salary", icon: "Briefcase", color: "#10B981", isRolloverEnabled: false, isHidden: false, sortOrder: 1 },
  { id: "cat-invest-income", groupId: "cg-income", name: "Dividends & Interest", icon: "TrendingUp", color: "#059669", isRolloverEnabled: false, isHidden: false, sortOrder: 2 },
  { id: "cat-other-income", groupId: "cg-income", name: "Other Income / Bonus", icon: "Gift", color: "#34D399", isRolloverEnabled: false, isHidden: false, sortOrder: 3 },

  // Fixed Expenses
  { id: "cat-rent-mortgage", groupId: "cg-fixed", name: "Rent & Mortgage", icon: "Home", color: "#6366F1", isRolloverEnabled: false, isHidden: false, sortOrder: 1 },
  { id: "cat-utilities", groupId: "cg-fixed", name: "Utilities (Electric, Gas, Water)", icon: "Zap", color: "#818CF8", isRolloverEnabled: true, isHidden: false, sortOrder: 2 },
  { id: "cat-internet", groupId: "cg-fixed", name: "Internet & Phone", icon: "Wifi", color: "#A5B4FC", isRolloverEnabled: false, isHidden: false, sortOrder: 3 },
  { id: "cat-insurance", groupId: "cg-fixed", name: "Insurance (Health, Auto, Home)", icon: "ShieldCheck", color: "#4F46E5", isRolloverEnabled: false, isHidden: false, sortOrder: 4 },

  // Variable Expenses
  { id: "cat-groceries", groupId: "cg-variable", name: "Groceries & Supermarkets", icon: "ShoppingCart", color: "#F59E0B", isRolloverEnabled: true, isHidden: false, sortOrder: 1 },
  { id: "cat-restaurants", groupId: "cg-variable", name: "Restaurants & Dining Out", icon: "Utensils", color: "#FBBF24", isRolloverEnabled: true, isHidden: false, sortOrder: 2 },
  { id: "cat-coffee", groupId: "cg-variable", name: "Coffee Shops & Bakeries", icon: "Coffee", color: "#D97706", isRolloverEnabled: true, isHidden: false, sortOrder: 3 },
  { id: "cat-transport", groupId: "cg-variable", name: "Gas, Fuel & Transit", icon: "Car", color: "#EC4899", isRolloverEnabled: true, isHidden: false, sortOrder: 4 },
  { id: "cat-shopping", groupId: "cg-variable", name: "Shopping & Electronics", icon: "ShoppingBag", color: "#F43F5E", isRolloverEnabled: true, isHidden: false, sortOrder: 5 },

  // Non-Monthly / Discretionary
  { id: "cat-travel", groupId: "cg-nonmonthly", name: "Travel, Flights & Hotels", icon: "Plane", color: "#8B5CF6", isRolloverEnabled: true, isHidden: false, sortOrder: 1 },
  { id: "cat-entertainment", groupId: "cg-nonmonthly", name: "Entertainment & Events", icon: "Film", color: "#A855F7", isRolloverEnabled: true, isHidden: false, sortOrder: 2 },
  { id: "cat-subscriptions", groupId: "cg-nonmonthly", name: "Software & Subscriptions", icon: "Tv", color: "#7C3AED", isRolloverEnabled: false, isHidden: false, sortOrder: 3 },
  { id: "cat-fitness", groupId: "cg-nonmonthly", name: "Gym & Fitness", icon: "Dumbbell", color: "#06B6D4", isRolloverEnabled: false, isHidden: false, sortOrder: 4 },
];

export const SEED_ACCOUNTS: AccountDto[] = [
  {
    id: "acc-chase-checking",
    userId: "user-admin",
    plaidItemId: "plaid-item-chase",
    plaidAccountId: "plaid-acc-chase-chk",
    institutionName: "Chase",
    name: "Total Checking",
    officialName: "Chase Premier Platinum Checking",
    mask: "4821",
    type: "DEPOSITORY",
    subtype: "checking",
    currentBalance: 8420.50,
    availableBalance: 8420.50,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-ally-savings",
    userId: "user-admin",
    plaidItemId: "plaid-item-ally",
    plaidAccountId: "plaid-acc-ally-sav",
    institutionName: "Ally Bank",
    name: "High Yield Savings",
    officialName: "Ally Online Savings Account",
    mask: "9102",
    type: "DEPOSITORY",
    subtype: "savings",
    currentBalance: 34500.00,
    availableBalance: 34500.00,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-vanguard-brokerage",
    userId: "user-admin",
    plaidItemId: "plaid-item-vanguard",
    plaidAccountId: "plaid-acc-vg-tax",
    institutionName: "Vanguard",
    name: "Individual Brokerage",
    officialName: "Vanguard Taxable Brokerage",
    mask: "3319",
    type: "INVESTMENT",
    subtype: "brokerage",
    currentBalance: 112850.75,
    availableBalance: 112850.75,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-fidelity-401k",
    userId: "user-admin",
    plaidItemId: "plaid-item-fidelity",
    plaidAccountId: "plaid-acc-fid-401k",
    institutionName: "Fidelity",
    name: "Employer 401(k)",
    officialName: "Fidelity Retirement Services 401(k)",
    mask: "7704",
    type: "INVESTMENT",
    subtype: "401k",
    currentBalance: 86400.20,
    availableBalance: 86400.20,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-amex-gold",
    userId: "user-admin",
    plaidItemId: "plaid-item-amex",
    plaidAccountId: "plaid-acc-amex-gold",
    institutionName: "American Express",
    name: "Amex Gold Card",
    officialName: "American Express Premier Rewards Gold",
    mask: "1004",
    type: "CREDIT",
    subtype: "credit card",
    currentBalance: 1845.30,
    availableBalance: 8154.70,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-chase-sapphire",
    userId: "user-admin",
    plaidItemId: "plaid-item-chase",
    plaidAccountId: "plaid-acc-chase-csr",
    institutionName: "Chase",
    name: "Sapphire Preferred",
    officialName: "Chase Sapphire Preferred Visa",
    mask: "6299",
    type: "CREDIT",
    subtype: "credit card",
    currentBalance: 1220.80,
    availableBalance: 18779.20,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "acc-mortgage",
    userId: "user-admin",
    plaidItemId: "plaid-item-wells",
    plaidAccountId: "plaid-acc-wells-mtg",
    institutionName: "Wells Fargo",
    name: "Home Mortgage 30Y",
    officialName: "Wells Fargo Fixed Rate Home Loan",
    mask: "8412",
    type: "LOAN",
    subtype: "mortgage",
    currentBalance: 245000.00,
    availableBalance: null,
    isoCurrencyCode: "USD",
    isHidden: false,
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_TRANSACTIONS: TransactionDto[] = [
  {
    id: "tx-1",
    userId: "user-admin",
    accountId: "acc-chase-checking",
    categoryId: "cat-paycheck",
    date: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    amount: -4500.00,
    originalName: "ACME CORP DIR DEP DIRECT DEPOSIT PPD ID: 994829104",
    cleanName: "Acme Corp Payroll",
    merchantName: "Acme Corp",
    pending: false,
    notes: "Bi-weekly salary payout",
    tags: ["income", "salary"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-2",
    userId: "user-admin",
    accountId: "acc-amex-gold",
    categoryId: "cat-groceries",
    date: new Date(Date.now() - 1 * 86400000).toISOString().split("T")[0],
    amount: 142.60,
    originalName: "WHOLEFDS SOMA #10243 SAN FRANCISCO CA",
    cleanName: "Whole Foods Market",
    merchantName: "Whole Foods Market",
    pending: false,
    notes: "Weekly organic groceries",
    tags: ["weekly"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-3",
    userId: "user-admin",
    accountId: "acc-amex-gold",
    categoryId: "cat-restaurants",
    date: new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0],
    amount: 88.50,
    originalName: "SQ *BLUE BOTTLE KITCHEN SF CA",
    cleanName: "Blue Bottle Cafe & Dinner",
    merchantName: "Blue Bottle Coffee",
    pending: false,
    notes: "Dinner with team",
    tags: ["dining"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-4",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-shopping",
    date: new Date(Date.now() - 4 * 86400000).toISOString().split("T")[0],
    amount: 185.00,
    originalName: "TARGET T-0941 SAN FRANCISCO CA",
    cleanName: "Target Superstore",
    merchantName: "Target",
    pending: false,
    notes: "Split between Groceries ($85) and Household Shopping ($100)",
    tags: ["split-receipt"],
    isExcludedFromBudget: false,
    isSplit: true,
    splits: [
      { id: "split-1", transactionId: "tx-4", categoryId: "cat-groceries", amount: 85.00, notes: "Groceries & Snacks" },
      { id: "split-2", transactionId: "tx-4", categoryId: "cat-shopping", amount: 100.00, notes: "Towels & Home Decor" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-5",
    userId: "user-admin",
    accountId: "acc-chase-checking",
    categoryId: "cat-rent-mortgage",
    date: new Date(Date.now() - 10 * 86400000).toISOString().split("T")[0],
    amount: 2200.00,
    originalName: "WELLS FARGO HOME MTG AUTO-PAY #8412",
    cleanName: "Wells Fargo Mortgage",
    merchantName: "Wells Fargo Mortgage",
    pending: false,
    notes: "Monthly mortgage payment",
    tags: ["fixed"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-6",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-subscriptions",
    date: new Date(Date.now() - 6 * 86400000).toISOString().split("T")[0],
    amount: 19.99,
    originalName: "NETFLIX.COM DIGITAL STREAMING NETFLIX US",
    cleanName: "Netflix Premium",
    merchantName: "Netflix",
    pending: false,
    notes: "Monthly subscription",
    tags: ["subscription"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-7",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-subscriptions",
    date: new Date(Date.now() - 8 * 86400000).toISOString().split("T")[0],
    amount: 14.99,
    originalName: "SPOTIFY USA PREMIUM MONTHLY SUBSCRIPTION",
    cleanName: "Spotify Premium",
    merchantName: "Spotify",
    pending: false,
    notes: "Music streaming",
    tags: ["subscription"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-8",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-travel",
    date: new Date(Date.now() - 12 * 86400000).toISOString().split("T")[0],
    amount: 340.00,
    originalName: "DELTA AIR LINES 00624918239 ATLANTA GA",
    cleanName: "Delta Air Lines",
    merchantName: "Delta Air Lines",
    pending: false,
    notes: "Weekend trip flight",
    tags: ["vacation"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-9",
    userId: "user-admin",
    accountId: "acc-amex-gold",
    categoryId: "cat-coffee",
    date: new Date(Date.now() - 5 * 86400000).toISOString().split("T")[0],
    amount: 6.75,
    originalName: "STARBUCKS STORE #19482 SAN FRANCISCO CA",
    cleanName: "Starbucks Coffee",
    merchantName: "Starbucks",
    pending: false,
    notes: "Morning latte",
    tags: ["coffee"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx-10",
    userId: "user-admin",
    accountId: "acc-chase-checking",
    categoryId: "cat-utilities",
    date: new Date(Date.now() - 15 * 86400000).toISOString().split("T")[0],
    amount: 145.20,
    originalName: "PG&E PACIFIC GAS & ELECTRIC ONLINE BILL",
    cleanName: "PG&E Utilities",
    merchantName: "PG&E",
    pending: false,
    notes: "Electric and gas bill",
    tags: ["utilities"],
    isExcludedFromBudget: false,
    isSplit: false,
    createdAt: new Date().toISOString(),
  },
];

export const SEED_BUDGETS: BudgetDto[] = [
  // Income targets
  { id: "b-1", userId: "user-admin", categoryId: "cat-paycheck", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 9000, rolloverAmount: 0 },
  { id: "b-2", userId: "user-admin", categoryId: "cat-invest-income", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 350, rolloverAmount: 0 },

  // Fixed Expense targets
  { id: "b-3", userId: "user-admin", categoryId: "cat-rent-mortgage", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 2200, rolloverAmount: 0 },
  { id: "b-4", userId: "user-admin", categoryId: "cat-utilities", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 200, rolloverAmount: 45 },
  { id: "b-5", userId: "user-admin", categoryId: "cat-internet", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 85, rolloverAmount: 0 },
  { id: "b-6", userId: "user-admin", categoryId: "cat-insurance", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 310, rolloverAmount: 0 },

  // Variable Expense targets
  { id: "b-7", userId: "user-admin", categoryId: "cat-groceries", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 650, rolloverAmount: 75 },
  { id: "b-8", userId: "user-admin", categoryId: "cat-restaurants", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 400, rolloverAmount: -30 },
  { id: "b-9", userId: "user-admin", categoryId: "cat-coffee", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 60, rolloverAmount: 12 },
  { id: "b-10", userId: "user-admin", categoryId: "cat-transport", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 180, rolloverAmount: 20 },
  { id: "b-11", userId: "user-admin", categoryId: "cat-shopping", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 300, rolloverAmount: -50 },

  // Non-monthly targets
  { id: "b-12", userId: "user-admin", categoryId: "cat-travel", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 500, rolloverAmount: 620 },
  { id: "b-13", userId: "user-admin", categoryId: "cat-entertainment", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 150, rolloverAmount: 40 },
  { id: "b-14", userId: "user-admin", categoryId: "cat-subscriptions", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 65, rolloverAmount: 0 },
  { id: "b-15", userId: "user-admin", categoryId: "cat-fitness", year: new Date().getFullYear(), month: new Date().getMonth() + 1, budgetedAmount: 90, rolloverAmount: 0 },
];

export const SEED_RULES: RuleDto[] = [
  {
    id: "rule-1",
    userId: "user-admin",
    name: "Auto-categorize Whole Foods to Groceries",
    priority: 10,
    conditions: [{ field: "merchant", operator: "contains", value: "whole foods" }],
    actions: [
      { type: "set_category", value: "cat-groceries" },
      { type: "rename_merchant", value: "Whole Foods Market" },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "rule-2",
    userId: "user-admin",
    name: "Auto-categorize Starbucks to Coffee",
    priority: 10,
    conditions: [{ field: "merchant", operator: "contains", value: "starbucks" }],
    actions: [
      { type: "set_category", value: "cat-coffee" },
      { type: "rename_merchant", value: "Starbucks" },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "rule-3",
    userId: "user-admin",
    name: "Auto-categorize Netflix to Subscriptions",
    priority: 10,
    conditions: [{ field: "merchant", operator: "contains", value: "netflix" }],
    actions: [
      { type: "set_category", value: "cat-subscriptions" },
      { type: "rename_merchant", value: "Netflix" },
      { type: "add_tag", value: "subscription" },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const SEED_RECURRING: RecurringItemDto[] = [
  {
    id: "rec-1",
    userId: "user-admin",
    accountId: "acc-chase-checking",
    categoryId: "cat-rent-mortgage",
    merchantName: "Wells Fargo Mortgage",
    expectedAmount: 2200.00,
    frequency: "MONTHLY",
    nextDate: new Date(Date.now() + 12 * 86400000).toISOString().split("T")[0],
    lastDate: new Date(Date.now() - 18 * 86400000).toISOString().split("T")[0],
    isActive: true,
  },
  {
    id: "rec-2",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-subscriptions",
    merchantName: "Netflix",
    expectedAmount: 19.99,
    frequency: "MONTHLY",
    nextDate: new Date(Date.now() + 24 * 86400000).toISOString().split("T")[0],
    lastDate: new Date(Date.now() - 6 * 86400000).toISOString().split("T")[0],
    isActive: true,
  },
  {
    id: "rec-3",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-subscriptions",
    merchantName: "Spotify",
    expectedAmount: 14.99,
    frequency: "MONTHLY",
    nextDate: new Date(Date.now() + 22 * 86400000).toISOString().split("T")[0],
    lastDate: new Date(Date.now() - 8 * 86400000).toISOString().split("T")[0],
    isActive: true,
  },
  {
    id: "rec-4",
    userId: "user-admin",
    accountId: "acc-chase-sapphire",
    categoryId: "cat-fitness",
    merchantName: "Equinox Gym",
    expectedAmount: 89.00,
    frequency: "MONTHLY",
    nextDate: new Date(Date.now() + 5 * 86400000).toISOString().split("T")[0],
    lastDate: new Date(Date.now() - 25 * 86400000).toISOString().split("T")[0],
    isActive: true,
  },
];

export function generateSeedNetWorthHistory(): NetWorthPoint[] {
  const points: NetWorthPoint[] = [];
  const now = new Date();
  
  // Generate 12 months of historical snapshots
  for (let i = 12; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const dateStr = d.toISOString().split("T")[0];

    // Simulating realistic market & savings growth
    const growthMultiplier = 1 + (12 - i) * 0.015;
    const cash = 42000 + (12 - i) * 800;
    const investments = 175000 * growthMultiplier + (Math.sin(i) * 3500);
    const totalAssets = cash + investments;
    const mortgage = 252000 - (12 - i) * 600;
    const credit = 2800 + (i % 2 === 0 ? 500 : -200);
    const totalLiabilities = mortgage + credit;
    const netWorth = totalAssets - totalLiabilities;

    points.push({
      date: dateStr,
      netWorth: Math.round(netWorth),
      assets: Math.round(totalAssets),
      liabilities: Math.round(totalLiabilities),
    });
  }

  return points;
}
